version: "1.0"
services:
  data-extraction-manager:
    build:
      context: ./data-extraction-manager
    container_name: data-extraction-manager
    volumes:
      - data:/data-extraction-manager/data
    env_file:
      - .env

  sentiment-analysis-manager:
    build:
      context: ./sentiment-analysis-manager
    container_name: sentiment-analysis-manager
    volumes:
      - data:/sentiment-analysis-manager/data
    env_file:
      - .env
    depends_on:
      - data-extraction-manager

volumes:
  data:
